<?php
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Api\{AuthController,AdminAuthController,ProductController,CategoryController,BannerController,SettingsController,CouponController,ComplaintController,OrderController,WishlistController,UploadController,LegacyController};
Route::get('/health', fn()=>response()->json(['ok'=>true,'data'=>['service'=>'fol-bazar-laravel-api','version'=>'1.0.0']]));
Route::post('/admin/login',[AdminAuthController::class,'login']);Route::prefix('auth')->group(function(){Route::post('/register',[AuthController::class,'register']);Route::post('/login',[AuthController::class,'login']);Route::get('/me',[AuthController::class,'me'])->middleware('auth:sanctum');Route::post('/logout',[AuthController::class,'logout'])->middleware('auth:sanctum');});
Route::get('/products',[ProductController::class,'index']);Route::get('/products/{product:slug}',[ProductController::class,'show']);Route::get('/categories',[CategoryController::class,'index']);Route::get('/categories/{category:slug}',[CategoryController::class,'show']);Route::get('/banners',[BannerController::class,'index']);Route::get('/settings',[SettingsController::class,'index']);
// Legacy frontend compatibility endpoints
Route::match(['GET','POST'],'/auth.php',[LegacyController::class,'auth']);
Route::get('/products.php',[LegacyController::class,'products']);Route::get('/categories.php',[LegacyController::class,'categories']);Route::get('/banners.php',[LegacyController::class,'banners']);Route::get('/coupons.php',[LegacyController::class,'coupons']);
Route::get('/orders.php',[OrderController::class,'track']);Route::get('/orders/track',[OrderController::class,'track']);Route::post('/orders.php',[OrderController::class,'store']);Route::post('/orders',[OrderController::class,'store']);Route::post('/complaints.php',[LegacyController::class,'complaints']);
Route::post('/complaints',[ComplaintController::class,'store']);
Route::post('/coupons/validate',[CouponController::class,'validateCoupon']);
Route::middleware('auth:sanctum')->group(function(){Route::get('/orders/my',[OrderController::class,'index']);Route::get('/orders/{order}',[OrderController::class,'show']);Route::get('/complaints',[ComplaintController::class,'index']);Route::apiResource('wishlist',WishlistController::class)->only(['index','store','destroy']);});
// File uploads are administrative operations only. Customer complaint images use /api/complaints.
Route::post('/upload',[UploadController::class,'store'])->middleware(['auth:sanctum','admin']);
// Legacy management endpoints are retained only for backward compatibility and are admin-only.
Route::match(['GET','POST','PUT','PATCH','DELETE'],'/manage.php',[LegacyController::class,'manage'])->middleware(['auth:sanctum','admin']);
Route::match(['GET','POST'],'/admin.php',[LegacyController::class,'admin'])->middleware(['auth:sanctum','admin']);
Route::match(['GET','POST','PATCH','DELETE'],'/admin-data',[\App\Http\Controllers\Admin\AdminDataController::class,'handle'])->middleware(['auth:sanctum','admin']);Route::prefix('admin')->middleware(['auth:sanctum','admin'])->group(function(){Route::get('/dashboard',[\App\Http\Controllers\Admin\DashboardController::class,'index']);Route::apiResource('products',\App\Http\Controllers\Admin\ProductController::class);Route::apiResource('categories',\App\Http\Controllers\Admin\CategoryController::class);Route::apiResource('orders',\App\Http\Controllers\Admin\OrderController::class)->only(['index','show','update']);Route::apiResource('customers',\App\Http\Controllers\Admin\UserController::class)->only(['index','show','update']);Route::apiResource('coupons',\App\Http\Controllers\Admin\CouponController::class);Route::apiResource('banners',\App\Http\Controllers\Admin\BannerController::class);Route::get('/settings',[\App\Http\Controllers\Admin\SettingsController::class,'index']);Route::put('/settings',[\App\Http\Controllers\Admin\SettingsController::class,'update']);});
